import { useEffect, useMemo, useRef, useState } from 'react';
import { Arrow, Circle, Group, Image as KonvaImage, Layer, Rect, Stage, Text } from 'react-konva';
import { createId, normalizeRect, type Annotation, type AnnotationGeometry } from '@marker/shared';
import { Card } from '@/components/ui/card';
import { useLoadedImage } from '@/lib/useLoadedImage';
import { useEditorStore } from '@/lib/useEditorStore';

const WIDTH = 960;
const HEIGHT = 560;
const PADDING = 24;
const fitImage = (imageWidth: number, imageHeight: number) => { const availableWidth = WIDTH - PADDING * 2; const availableHeight = HEIGHT - PADDING * 2; const scale = Math.min(availableWidth / imageWidth, availableHeight / imageHeight, 1); const width = imageWidth * scale; const height = imageHeight * scale; return { x: (WIDTH - width) / 2, y: (HEIGHT - height) / 2, width, height }; };
const getDefaultStyle = (tool: Annotation['tool']) => tool === 'highlight' ? { stroke: '#f59e0b', fill: 'rgba(251,191,36,0.25)', strokeWidth: 3 } : tool === 'blur' ? { stroke: '#0f172a', fill: 'rgba(15,23,42,0.45)', strokeWidth: 2 } : tool === 'arrow' ? { stroke: '#2563eb', strokeWidth: 4 } : tool === 'marker' ? { stroke: '#2563eb', fill: '#2563eb', strokeWidth: 2 } : tool === 'text' ? { stroke: '#2563eb', fill: 'rgba(255,255,255,0.95)', strokeWidth: 2 } : { stroke: '#ef4444', fill: 'rgba(239,68,68,0.08)', strokeWidth: 3 };
const buildAnnotation = (tool: Annotation['tool'], geometry: AnnotationGeometry, assetId: string, index: number): Annotation => ({ id: createId('annotation'), assetId, tool, geometry, label: tool === 'marker' ? String(index) : tool === 'text' ? `Text ${index}` : undefined, style: getDefaultStyle(tool), createdAt: new Date().toISOString() });

export function AnnotationCanvas({ readOnly = false, onExportReady }: { readOnly?: boolean; onExportReady?: (exporter: () => string | undefined) => void; }) {
  const stageRef = useRef<any>(null);
  const draft = useEditorStore((state) => state.draft);
  const activeTool = useEditorStore((state) => state.activeTool);
  const selectedAnnotationId = useEditorStore((state) => state.selectedAnnotationId);
  const zoom = useEditorStore((state) => state.zoom);
  const addAnnotation = useEditorStore((state) => state.addAnnotation);
  const updateAnnotation = useEditorStore((state) => state.updateAnnotation);
  const setSelectedAnnotation = useEditorStore((state) => state.setSelectedAnnotation);
  const image = useLoadedImage(draft.asset?.imageDataUrl);
  const [dragStart, setDragStart] = useState<{ x: number; y: number } | null>(null);
  const [preview, setPreview] = useState<Annotation | null>(null);
  const imageBounds = useMemo(() => draft.asset ? fitImage(draft.asset.width, draft.asset.height) : null, [draft.asset]);
  useEffect(() => { onExportReady?.(() => stageRef.current?.toDataURL({ pixelRatio: 2 })); }, [onExportReady]);
  const getPointer = () => { const stage = stageRef.current; const pointer = stage?.getPointerPosition(); return pointer ? { x: pointer.x / zoom, y: pointer.y / zoom } : null; };
  const markerCount = draft.annotations.filter((annotation) => annotation.tool === 'marker').length + 1;
  const commitPreview = () => { if (preview) addAnnotation(preview); setPreview(null); setDragStart(null); };
  const startDrawing = () => { if (readOnly || !draft.asset) return; const pointer = getPointer(); if (!pointer) return; if (activeTool === 'select') { setPreview(null); return; } if (activeTool === 'marker') { addAnnotation(buildAnnotation('marker', { kind: 'marker', x: pointer.x, y: pointer.y }, draft.asset.id, markerCount)); return; } if (activeTool === 'text') { const body = window.prompt('Text note', 'Add note'); if (!body) return; addAnnotation({ ...buildAnnotation('text', { kind: 'text', x: pointer.x, y: pointer.y, width: 180, height: 72 }, draft.asset.id, draft.annotations.length + 1), label: body }); return; } setDragStart(pointer); };
  const updatePreview = () => { if (!dragStart || readOnly || !draft.asset || activeTool === 'select' || activeTool === 'text' || activeTool === 'marker') return; const pointer = getPointer(); if (!pointer) return; const geometry = activeTool === 'arrow' ? { kind: 'arrow' as const, points: [dragStart.x, dragStart.y, pointer.x, pointer.y] as [number, number, number, number] } : normalizeRect({ x1: dragStart.x, y1: dragStart.y, x2: pointer.x, y2: pointer.y }); setPreview(buildAnnotation(activeTool as Annotation['tool'], geometry, draft.asset.id, draft.annotations.length + 1)); };
  const renderAnnotation = (annotation: Annotation, isPreview = false) => { const selected = annotation.id === selectedAnnotationId; switch (annotation.tool) { case 'rectangle': case 'highlight': case 'blur': { const geometry = annotation.geometry; if (geometry.kind !== 'rect') return null; return <Group key={annotation.id} x={geometry.x} y={geometry.y} draggable={!readOnly && activeTool === 'select' && !isPreview} onClick={() => setSelectedAnnotation(annotation.id)} onTap={() => setSelectedAnnotation(annotation.id)} onDragEnd={(event) => { const pos = event.target.position(); updateAnnotation(annotation.id, (current) => { if (current.geometry.kind === 'rect') current.geometry = { ...current.geometry, x: pos.x, y: pos.y }; }); }}><Rect width={geometry.width} height={geometry.height} stroke={annotation.style.stroke} strokeWidth={annotation.style.strokeWidth ?? 2} fill={annotation.style.fill} dash={selected ? [8, 6] : undefined} cornerRadius={8} /></Group>; }
    case 'arrow': { const geometry = annotation.geometry; if (geometry.kind !== 'arrow') return null; return <Arrow key={annotation.id} points={geometry.points} stroke={annotation.style.stroke} fill={annotation.style.stroke} pointerLength={10} pointerWidth={10} strokeWidth={annotation.style.strokeWidth ?? 4} onClick={() => setSelectedAnnotation(annotation.id)} onTap={() => setSelectedAnnotation(annotation.id)} dash={selected ? [8, 6] : undefined} />; }
    case 'marker': { const geometry = annotation.geometry; if (geometry.kind !== 'marker') return null; return <Group key={annotation.id} x={geometry.x} y={geometry.y} draggable={!readOnly && activeTool === 'select' && !isPreview} onClick={() => setSelectedAnnotation(annotation.id)} onTap={() => setSelectedAnnotation(annotation.id)} onDragEnd={(event) => { const pos = event.target.position(); updateAnnotation(annotation.id, (current) => { if (current.geometry.kind === 'marker') current.geometry = { ...current.geometry, x: pos.x, y: pos.y }; }); }}><Circle radius={16} fill="#2563eb" stroke={selected ? '#0f172a' : '#ffffff'} strokeWidth={selected ? 3 : 2} /><Text text={annotation.label ?? ''} x={-6} y={-8} fontStyle="bold" fill="#ffffff" /></Group>; }
    case 'text': { const geometry = annotation.geometry; if (geometry.kind !== 'text') return null; return <Group key={annotation.id} x={geometry.x} y={geometry.y} draggable={!readOnly && activeTool === 'select' && !isPreview} onClick={() => setSelectedAnnotation(annotation.id)} onTap={() => setSelectedAnnotation(annotation.id)} onDragEnd={(event) => { const pos = event.target.position(); updateAnnotation(annotation.id, (current) => { if (current.geometry.kind === 'text') current.geometry = { ...current.geometry, x: pos.x, y: pos.y }; }); }}><Rect width={geometry.width} height={geometry.height} fill={annotation.style.fill} stroke={annotation.style.stroke} strokeWidth={annotation.style.strokeWidth ?? 2} cornerRadius={10} dash={selected ? [8, 6] : undefined} /><Text text={annotation.label ?? ''} x={12} y={12} width={geometry.width - 24} fill="#0f172a" fontSize={14} /></Group>; }
  }};
  return <Card className="overflow-hidden p-4"><Stage ref={stageRef} width={WIDTH} height={HEIGHT} scaleX={zoom} scaleY={zoom} className="rounded-2xl bg-slate-100" onMouseDown={startDrawing} onMouseMove={updatePreview} onMouseUp={commitPreview} onClick={(event) => { if (event.target === event.target.getStage()) setSelectedAnnotation(null); }}><Layer><Rect width={WIDTH} height={HEIGHT} fill="#e2e8f0" cornerRadius={18} />{image && imageBounds ? <KonvaImage image={image} x={imageBounds.x} y={imageBounds.y} width={imageBounds.width} height={imageBounds.height} cornerRadius={18} /> : null}{draft.annotations.map((annotation) => renderAnnotation(annotation))}{preview ? renderAnnotation(preview, true) : null}</Layer></Stage></Card>;
}
